pipeline {
    agent {
        label 'build-server'
    }
    stages {
        stage('info') {
            steps {
                sh(script: """whoami;pwd;ls -la""", label: "first stage")
            }
        }
    }
}
